classdef SpectroscopyData < handle
    properties
        hf1;
        p;
        X;
        Y;
        V;
        LS;
        LS_realspace;
        qx;
        qy
        I;
        I_cropped;
        X_cropped;
        Y_cropped;
        LS_cropped;
        LS_fft;
        ctr;
        hi1;
        ax1;
        hi2;
        ax2;
        slider;
        crop_button;
        reset_button;
        roi_imrect_handle;
        data;
    end
    methods
        
    end
end