classdef SpectroscopyData < handle
    properties
        hf1;
        p;
        X;
        Y;
        Z;
        V;
        LS;
        LS_realspace;
        qx;
        qy
        I;
        I_cropped;
        I_slice;
        X_cropped;
        Y_cropped;
        Z_cropped;
        LS_cropped;
        LS_fft;
        LS_realspace_cropped;
        I_slice_cropped;
        ctr;
        hi1;
        ax1;
        hi2;
        ax2;
        slider;
        crop_button;
        crop_pos;
        reset_button;
        roi_imrect_handle;
        data;
    end
    methods
        
    end
end